import { describe, expect, it } from 'vitest';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const {
  normalizeLabels,
  hasCopilotSignal,
  getPullSource,
  issuePriority,
  buildPriorityIssues,
  summarizeNextSteps,
  computeNextStepState
} = require('../scripts/fetch-data.js');

describe('fetch-data heuristics', () => {
  it('normalizes mixed label shapes', () => {
    expect(normalizeLabels(['bug', { name: 'priority:high' }, { nope: true }])).toEqual([
      'bug',
      'priority:high'
    ]);
  });

  it('detects copilot signal from pull metadata', () => {
    const pull = {
      user: { login: 'someone' },
      head: { ref: 'copilot/fix-issue' },
      title: 'Refactor dashboard'
    };
    expect(hasCopilotSignal('Generated by Copilot')).toBe(true);
    expect(getPullSource(pull, [])).toBe('copilot');
  });

  it('prioritizes issues by label severity and triage state', () => {
    const critical = issuePriority({
      labels: [{ name: 'sev:critical' }],
      created_at: '2026-05-20T00:00:00.000Z',
      assignees: [{}]
    });
    const triage = issuePriority({
      labels: [],
      created_at: '2026-05-20T00:00:00.000Z',
      assignees: []
    });

    expect(critical.reason).toBe('critical-label');
    expect(critical.score).toBeGreaterThan(triage.score);
    expect(triage.reason).toBe('needs-triage');
  });

  it('builds sorted priority issue list and enforces cap', () => {
    const issues = [
      { number: 1, title: 'A', html_url: 'u1', labels: [{ name: 'priority:high' }], created_at: '2026-05-01T00:00:00.000Z', assignees: [{}] },
      { number: 2, title: 'B', html_url: 'u2', labels: [{ name: 'bug' }], created_at: '2026-05-02T00:00:00.000Z', assignees: [{}] },
      { number: 3, title: 'C', html_url: 'u3', labels: [], created_at: '2026-05-03T00:00:00.000Z', assignees: [] },
      { number: 4, title: 'D', html_url: 'u4', labels: [{ name: 'sev:critical' }], created_at: '2026-05-04T00:00:00.000Z', assignees: [{}] }
    ];

    const ranked = buildPriorityIssues(issues);
    expect(ranked).toHaveLength(3);
    expect(ranked[0].number).toBe(1);
    expect(ranked.map((i) => i.number)).toContain(4);
  });

  it('summarizes next steps with highest-risk signals first', () => {
    const summary = summarizeNextSteps({
      releaseOverdue: true,
      pendingReviewCount: 2,
      triageIssueCount: 1,
      copilotWorkReady: true,
      squadWorkReady: false,
      hasRecentActivity: true,
      hasRelease: true,
      securityAlerts: { critical: 1, high: 0 },
      ciFailure: true,
      manyBranches: true
    });

    expect(summary).toContain('CI is failing');
    expect(summary).toContain('1 critical security alert');
    expect(summary).toContain('Release is overdue');
    expect(summary).toContain('2 PRs need review');
  });

  it('derives fallback next-step state when no explicit signals exist', () => {
    expect(computeNextStepState([], true)).toEqual({ status: 'active', signals: ['active'] });
    expect(computeNextStepState([], false)).toEqual({ status: 'quiet', signals: ['quiet'] });
    expect(computeNextStepState(['ci-failing'], true)).toEqual({
      status: 'needs-attention',
      signals: ['ci-failing']
    });
  });
});